#!/usr/bin/env php
<?php
$vendorAutoload=[
 __DIR__.'/../../autoload.php',
 getcwd().'/bootstrap.php',
];
foreach($vendorAutoload as$file){
 if(file_exists($file)){
  include($file);
 }
}

(new OceanWebTurk\OceanWebTurk())->run();
